PRAGMA foreign_keys=OFF;
DROP TRIGGER IF EXISTS trg_revenue_decisions_no_delete;
DROP TRIGGER IF EXISTS trg_revenue_decisions_append_only;
DROP TRIGGER IF EXISTS trg_revenue_positions_entry_immutable;
DROP TRIGGER IF EXISTS trg_revenue_positions_lifecycle_guard;
DROP TRIGGER IF EXISTS trg_revenue_positions_no_delete;
DROP TRIGGER IF EXISTS trg_revenue_evaluations_append_only;
DROP TRIGGER IF EXISTS trg_revenue_evaluations_no_delete;
DROP TRIGGER IF EXISTS trg_revenue_marks_append_only;
DROP TRIGGER IF EXISTS trg_revenue_marks_no_delete;
DROP TRIGGER IF EXISTS trg_revenue_marks_open_position_only;
DROP TRIGGER IF EXISTS trg_revenue_equity_append_only;
DROP TRIGGER IF EXISTS trg_revenue_equity_no_delete;
DROP TABLE IF EXISTS revenue_poc_api_calls;
DROP TABLE IF EXISTS revenue_poc_api_daily;
DROP TABLE IF EXISTS revenue_poc_equity_points;
DROP TABLE IF EXISTS revenue_poc_marks;
DROP TABLE IF EXISTS revenue_poc_decisions;
DROP TABLE IF EXISTS revenue_poc_positions;
DROP TABLE IF EXISTS revenue_poc_evaluations;
DROP TABLE IF EXISTS revenue_poc_accounts;
PRAGMA foreign_keys=ON;
